/**************************************************************************
	Dynamic Dialog Boxes Demo
	IDs Header File
	Written by Atif Aziz
**************************************************************************/

	// Control identifiers

#define IDC_PROPERTY		100
#define IDC_FRAME_DIALOGBOX	1000

#define IDC_STRIKEOUT		208
#define IDC_UNDERLINE		209
#define IDC_AUTOTEXT		316		
#define IDC_AUTOSIZE		317
#define IDC_SHADOW		403
