/**************************************************************************
	Dynamic Dialog Boxes Demo
	IDs Header File
	Written by Atif Aziz
**************************************************************************/

	// Control constants

#define IDC_PROPERTY		100
#define IDC_FRAME_DIALOGBOX	1000
#define IDC_FRAME_FONT		1001
#define IDC_FRAME_TEXT		1002
#define IDC_FRAME_PATTERNS	1003

#define IDC_FONT_FIRST		200
#define IDC_FONT_LAST		217
#define IDC_TEXT_FIRST		300
#define IDC_TEXT_LAST		317
#define IDC_PATTERNS_FIRST	400
#define IDC_PATTERNS_LAST	421
